# This is an example configuration file. You should customize these values and
# rename the file to 'config.yaml'.

# Set this to false when interacting with an authentication server that uses
# self-signed certificates. This should ONLY be done during testing.
strictHttpsValidation: false

# Authentication server iss value.
issuer: https://example.com
# Authentication server OAuth2/OpenID Connect endpoints.
authorizeEndpoint: https://example.com/oauth/authorize
tokenEndpoint: https://example.com/oauth/token
revokeEndpoint: https://example.com/oauth/revoke
logoutEndpoint: https://example.com/oauth/logout
jwksEndpoint: https://example.com/jwks
# Authentication server account management application.
accountManagerUri: https://example.com/samples/my-account
# Resource server SCIM endpoint.
scimEndpoint: https://example.com/scim/v2

# The JWA used to sign ID tokens for this application.
idTokenSigningAlgorithm: RS256

# Client credentials.
clientId: groovy-sign-in-sample
clientSecret: Srf9BGpgZqfu1TSI8gTFmX9in8B2Z1ox