# This is an example configuration file. You should customize these values and
# rename the file to 'config.yaml'.

# Set this to false when interacting with an authentication server that uses
# self-signed certificates. This should ONLY be done during testing.
strictHttpsValidation: false

# Authentication server iss value. This should have the form 'https://hostname'
issuer: https://example.com

# The base URI of the authentication server, with no path.
authenticationServerBaseUri: https://example.com/

# The base URI of the resource server, with no path.
resourceServerBaseUri: https://example.com/

# The full URI of an account management application.
accountManagerUri: https://example.com/samples/my-account

# The JWA used to sign ID tokens for this application.
idTokenSigningAlgorithm: RS256

# Client credentials.
clientId: groovy-sign-in-sample
clientSecret: Srf9BGpgZqfu1TSI8gTFmX9in8B2Z1ox